Removed forced use of lowercase for project directory name
theos/nic pull request #19
Opened 2024-05-28 03:40 UTC by Luki120

What does this implement/fix? Explain your changes.
---------------------------------------------------
* Removes the use of `lc()` around `$clean_project_name`, i.e the directory where the template will be created. If a user chooses to uppercase their project directory name, without this change `nic.pl` disregards that and lowercases the entire name, which most likely isn't what they would expect. If they want to add capital letters to their project name, they should be able to do so without later on having to rename the project manually. If they don't want to, then they'll probably won't in the first place, therefore `nic.pl` shouldn't lowercase it for them. I don't see why this is needed in the code, I don't think it breaks anything, so removing it in my opinion is a good idea, otherwise it's just forced and might be annoying for some users.

Does this close any currently open issues?
------------------------------------------
*

Any relevant logs, error output, etc?
-------------------------------------
*
Any other comments?
-------------------
*
Where has this been tested?
---------------------------
  **Operating System:** Ubuntu 22.04

**Platform:** WSL 2

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

2024-05-30 00:04 UTC, L1ghtmann requested changes
Thanks for the pr! I agree that nic should not be modifying the project name as it is provided. We will want to test this (`test.sh` from theos/templates) for Linux and OSX to ensure compatibility with the variable case sensitivities as this script was [initially created](https://github.com/theos/nic/commit/25615aa3fa785ab6c1579771f0f038b6c6c2c3b5) with the forced lowercase. Have one comment on the code and one regarding the modified permissions of the script. Thanks again!

2024-05-30 00:04 UTC, L1ghtmann commented on bin/nic.pl
> +promptIfMissing(\$package_name, $package_prefix.".".$clean_project_name, "Package Name") unless $NIC->variableIgnored("PACKAGENAME");
These changes introduce a dpkg control file incompatibility and do not affect the directory name.

2024-05-30 00:05 UTC, L1ghtmann reviewed
Please revert the changes to the script's permissions.

2024-06-01 02:48 UTC, leptos-null approved these changes
Looks good to me.
Tested on macOS with project name `TestTool` (`iphone/tool` template from `theos/templates`)

2024-06-01 10:27 UTC, uroboro approved these changes

2024-06-08 16:06 UTC, L1ghtmann approved these changes
Looks good, thanks! There was a slight concern about case-sensitivity but since nic is isolated I don't believe this possess any problems.

2024-06-08 16:07 UTC, merged